export const INITIAL_ROUTE = '/';
export const BREEDS_ROUTE = '/breeds';
export const GALLERY_ROUTE = '/gallery';
export const VOTING_ROUTE = '/voting';
export const LIKES_ROUTE = '/likes';
export const FAVORITES_ROUTE = '/favorites';
export const DISLIKES_ROUTE = '/dislikes';
export const SEARCH_ROUTE = '/search';
// export const _ROUTE = '/';
